{{- if .Values.envFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tdg-service.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tdg-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretData }}
  {{ $key }}: {{ $val }}
  {{- end }}
{{- end }}
